### ISSUE TITLE
Switch MLJBase dependency to MLJModelInterface

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJFlux.jl#10]
So MLJModelInterface is the new super light-weight alternative to MLJBase. Basically, the steps are:

- [ ] add MLJModelInteface.jl to project [deps]

- [ ] move MLJBase from [deps] to [extras] and [targets] (it is still needed to *test* the interface)

- [ ] replace "MLJBase" references in src/ to "MLJModelInterface"

Hopefully, this just works, but ping me with problems. See also [here](https://alan-turing-institute.github.io/MLJ.jl/dev/quick_start_guide_to_adding_models/)

**Comment by ayush-1506** [comment]
I'm facing a few issues while doing this, looks like a few methods aren't available/exposed in MLJModelInterface? I've replaced all instances of MLJBase with MLJModelInterface, but I get a few errors. For example, what is the equivalent of `MLJBase.schema` in MLJModelInterface?

**Comment by ablaom** [comment]
You are only using `schema(X).names` (no scitypes), so you can just use `Tables.schema` (you already have Tables as dep).

What else?

**Comment by ayush-1506** [comment]
Another quick question: I found two similar packages: MLJScientificTypes and ScientificTypes. Why are there two packages that seem to solve the same purpose? What am I missing here?

**Comment by ablaom** [comment]
ScientificTypes just defines the types (`Continuous`, `OrderedFactor`, etc). MLJScientificTypes implements the MLJ *convention* (ie defines the `scitype` function, so that, eg, `scitype(1.0) == Continuous` for otherwise `scitype(1.0) == Unknown`). You can define a different convention, starting with `ScientificTypes` although probably no-one will bother. We separated these as part of a restructuring that created the lightweight `MLJModelnterface`, which has `ScientificTypes` as it's sole dependency. 

MLJModelInterface loads in less than a tenth of the time MLJBase does. 

You can get an overview of the current code organisation [here](https://github.com/alan-turing-institute/MLJ.jl/blob/master/ORGANIZATION.md).

**Comment by ablaom** [comment]
Anything else?

**Comment by ayush-1506** [comment]
Thanks, that clarifies things! I followed the steps mentioned in the links you described. I've essentially replaced `MLJBase` -> `MLJModelInterface` in src/ , followed by a few miscellaneous changes (like `schema` above.). However, during testing, when I call `MLJBase.fit` (as it should be), I get an error:
```
ERROR: LoadError: LoadError: MethodError: no method matching 
fit(::MLJFlux.NeuralNetworkClassifier{MLJFlux.Linear,Flux.Optimise.ADAM,typeof(Flux.crossentropy)},
 ::Int64, ::NamedTuple{(:x1, :x2, :x3, :x4, :x5),NTuple{5,Array{Float64,1}}}, 
::CategoricalArray{Char,1,UInt32,Char,CategoricalValue{Char,UInt32},Union{}})
```

Not sure if I'm missing something here?

**Comment by ablaom** [comment]
I suggest you open a WIP PR and we go from there. This will be more efficient. Many thanks
