### ISSUE TITLE
Rename `epochs` to `n` ?

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJFlux.jl#29]
Iteration parameter in MLJ models is generally `n`, which is less typing. 

On the other hand `epochs` is relatively entrenched in Flux and DL community, yes?

**Comment by ayush-1506** [comment]
Yes, it's more common to use `epochs` or `n_epochs`. (Since `n` can mean many things). However, if it's better, we can switch to `n` here.

**Comment by ablaom** [comment]
Let's leave it `epochs`.
