### ISSUE TITLE
Extend ImageClassifier to color images

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJFlux.jl#4]
It seems to me that this just needs us to have two versions of  `make_minibatches`. So something like 

```julia
function make_minibatch(X::AbstractVector{<:GrayImage}, Y, idxs)
    X_batch = Array{Float32}(undef, size(X[1])..., 1, length(idxs))
    for i in 1:length(idxs)
        X_batch[:, :, :, i] = Float32.(X[idxs[i]])
    end
    Y_batch = Flux.onehotbatch(Y[idxs], 0:9)
    return (X_batch, Y_batch)
end
```

and

```julia
function make_minibatch(X::AbstractVector{<:ColorImage}, Y, idxs)
    X_batch = Array{Float32}(undef, size(X[1])..., length(idxs))
    for i in 1:length(idxs)
        X_batch[:, :, :, i] = Float32.(X[idxs[i]])
    end
    Y_batch = Flux.onehotbatch(Y[idxs], 0:9)
    return (X_batch, Y_batch)
end
```

Or some refactoring of this with less code repetition.

**Comment by ablaom** [comment]
@ayush-1506 While recent PR for images https://github.com/alan-turing-institute/MLJFlux.jl/issues/31 gets us close to resolving the current issue, there remains one wrinkle. I think we need:

- [ ] builders for image classification to include an `n_channels` argument in the `fit` signature (see my revision of the readme [here](https://github.com/alan-turing-institute/MLJFlux.jl/tree/dev#defining-a-new-builder)) 

- [ ] the `ImageClassfier` fit method to call the builder with this new information, inferred from the 

- [ ] a test for color images. We easily adapt the first existing test for for gray images

Thoughts?

**Comment by ayush-1506** [comment]
Closing in favor of #39 .
