### ISSUE TITLE
Name change fit(builder, ...) to chain(builder,...) ?

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJFlux.jl#40]
When reviewing the readme, I thought that `fit` is a bit confusing as we are not really training anything. Perhaps `chain` or `build` is better? 

If we use `chain`, it's probably best not to export the name. 

@ayush-1506 Thoughts?

**Comment by ayush-1506** [comment]
Yeah, plus there's always some confusion between `MMI.fit` and `MLJFlux.fit`. Perhaps using build seems like a better choice.

**Comment by ayush-1506** [comment]
#42 should fix this.
