### ISSUE TITLE
Get tests passing again

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJFlux.jl#5]
Here are some steps for restarting this package. I suggest you get a master branch with no feature embedding or one-hot encoding that passes all tests before creating a separate branch for feature embedding stuff. 

- [x] Remove all mention of UnivariateNeuralNetworkRegressor

- [x] Remove ` Val(ismulti)` bits of predictions for regressors. I have no idea what they are for and are breaking tests.

- [x] Split the current NeuralNetworkRegressor into two models with identical fields: NeuralNetworkRegressor (to handle univariate targets, which will always be vectors, both in training and prediction) and MultivariateNeuralNetwork (to handle multivariate targets, which will always be tables, both in training and prediction). Most of the `fit` code for these models is identical, but you can avoid code  duplication with appropriate auxiliary methods and clever dispatch. 

- [x] Define all package-specific traits with this declaration (check my spelling):

```julia
MLJBase.metadata_pkg.((NeuralNetworkRegressor, MultivariateNeuralNetworkRegressor, NeuralNetworkClassifier,ImageClassifier),
              name="MLJFlux",
              uuid="094fc8d1-fd35-5302-93ea-dabda2abf845"
              url="https://github.com/alan-turing-institute/MLJFlux.jl",
              julia=true,
              license="MIT")
```

See [here](https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/) for more on `metadata_pkg` or just query doc string.

- [x] Define model-specific traits with declarations like:

```julia
metadata_model(NeuralNetworkRegressor,
               input=MLJBase.Table(MLJBase.Continuous),
               target=AbstractVector{<:MLJBase.Continuous},
               path="MLJFlux.NeuralNetworkRegressor, 
               descr="A neural network model for making deterministic predictions of a `Continuous` multi-target, presented as a table,  given a table of `Continuous` features. "
```

The `path` and `desr` will be different for each of the four models, as will `target` which I will spell out below:

```julia
target=MLJBase.Table(Continuous)             # MultivariateNeuralNetworkRegressor
target=AbstractVector{<:MLJBase.Finite}   # NeuralNetworkClassifier
target=AbstractVector{<:GrayImage}          # ImageClassifier
```

The descriptions (in same order):

```julia 
descr="A neural network model for making deterministic predictions of a `Continuous` mutli-target, presented as a table,  given a table of `Continuous` features. "

descr="A neural network model for making probabilistic predictions of a `Mutliclass` or `OrderedFactor` target, given a table of `Continuous` features. "

descr="A neural network model for making probabilistic predictions of a `GreyImage` target, given a table of `Continuous` features. "
```

For now all models have the same `input` value.

**Comment by ablaom** [comment]
ping @ayush-1506

**Comment by ablaom** [comment]
@ayush-1506 Any chance you could take a look at these?

**Comment by ayush-1506** [comment]
@ablaom Yes, I did take a crack at some of these. Unfortunately I'm a bit busy at the moment. I'll definitely try to fix everything as soon as I can and push everything. In case you need something else in addition, kindly let me know. (Over here or on slack)

**Comment by ayush-1506** [comment]
I found some time and was able to make some progress. Most of what you mentioned in the above comment has been done. What remains is:
1. Implementing the suggested MultivariateNeuralNetwork struct.
2. Redefining the tests and getting them to pass.

I'm updating the master branch with these changes at the moment. All the earlier code (that consisted of entity embedding, one-hot related stuff) has been moved to the dev branch.

Apologies for the delay, I should be able to get everything running pretty soon.

**Comment by ayush-1506** [comment]
I found some time and was able to make some progress. Most of what you mentioned in the above comment has been done. What remains is:

    Implementing the suggested MultivariateNeuralNetwork struct.
    Redefining the tests and getting them to pass.

I'm updating the master branch with these changes at the moment. All the earlier code (that consisted of entity embedding, one-hot related stuff) has been moved to the dev branch.

I should be able to get everything running pretty soon.

**Comment by ayush-1506** [comment]
@ablaom I'm almost done with this, could you point out the key differences between NNRegressor and MultivariateNNRegressor. While working on MultivariateNNRegressor, the difference became a bit blurry to me and I lost track.

**Comment by ayush-1506** [comment]
Update: Done with multivariatennregressor. NNregressor and MultivariateNNRegressor now share most of the functions, with small changes.

**Comment by ablaom** [comment]
@ayush-1506 Many thanks! Be great if you can take a look at #6.
