### ISSUE TITLE
GPU issue: predict needs to move unwrapped matrix to GPU

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJFlux.jl#62]
I've started testing on GPU. The `fit` methods moves data to the GPU if necessary, but new input data `Xnew` provided to `predict` needs to be moved also, after converting to matrix. 

```
ArgumentError: cannot take the CPU address of a CuArrays.CuArray{Float32,2,Nothing}
```

**edit** This issue does not refer to the `master` branch or current release but to the `test-gpu` branch

**Comment by DilumAluthge** [comment]
We also need to think about serializing. If we train a model on the GPU, we need to move everything back to the CPU before we can save to disk.

In fact a full use case might look like this:
1. Load data on computer 1 (which has a GPU). Data starts out on disk. We load it from disk into CPU memory.
2. Move data from CPU to GPU in computer 1.
3. Use GPU to fit model in computer 1.
4. Move everything back to CPU in computer 1.
5. Serialize the model to disk in computer 1.
6. Copy the serialized model (which is on disk) from computer 1 to computer 2. Computer 2 does not have a GPU.
7. Load the serialized model from disk into CPU memory in computer 2.
8. Someone gives me some new data. I load this new data from disk into CPU memory in computer 2.
9. I want to call `predict`, using the new data (living in CPU memory in computer 2) and the serialized model (loaded into CPU memory in computer 2).

**Comment by ablaom** [comment]
Good point!

**Comment by ablaom** [comment]
I've been rethinking this and wonder if it wouldn't be better if learned parameters (the Flux chain) wouldn't be better off being moved to the cpu after every train (meaning prediction is always on the CPU). It seems to me that compared to training data, the learned parameters are small so it's better to move them than to keep moving the data (which is what will happen at #63 at the moment, unless the input `X` is a CUDAArray wrapped as a table). Of course training is far more expensive than prediction -  so no biggie there. This also means no special serialization logic. Some pure DL practioners might object but I think that from the point of the general user this might make more sense and a little more robust. 

@DilumAluthge  Your thoughts?

**Comment by DilumAluthge** [comment]
> I've been rethinking this and wonder if it wouldn't be better if learned parameters (the Flux chain) wouldn't be better off being moved to the cpu after every train (meaning prediction is always on the CPU).

I'm certainly far from an expert. But this makes sense to me. Training is the expensive part, so that's the part we want to do on the GPU. Prediction is fast in relation to training, so it makes sense to me to just always do prediction on the CPU.
