### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by OpenSuze** [alan-turing-institute/MLJFlux.jl#7]
Hi !

I tried MLJFlux two weeks ago on a machine and it was working great.

Now, I have another machine and I am not able to compile MLJFlux. I have tried to reinstall everything, but it doesn't have fixed my issue.

`julia> Pkg.clone("https://github.com/alan-turing-institute/MLJFlux.jl")`
`  Updating git-repo https://github.com/alan-turing-institute/MLJFlux.jl`
` Resolving package versions...`
`  Updating ~/.julia/environments/v1.3/Project.toml`
`  [094fc8d1] + MLJFlux v0.0.0 [~/.julia/dev/MLJFlux]`
`  Updating ~/.julia/environments/v1.3/Manifest.toml`
`  [094fc8d1] + MLJFlux v0.0.0 [~/.julia/dev/MLJFlux]`

`julia> Pkg.status()`
`    Status ~/.julia/environments/v1.3/Project.toml`
`  [b4f34e82] Distances v0.8.2`
`  [587475ba] Flux v0.8.3`
`  [c91e804a] Gadfly v1.2.0`
`  [7073ff75] IJulia v1.21.1`
`  [add582a8] MLJ v0.9.1`
`  [094fc8d1] MLJFlux v0.0.0 [~/.julia/dev/MLJFlux]`
`  [d491faf4] MLJModels v0.8.0`
`  [91a5bcdd] Plots v0.29.1`
`  [8162dcfd] PrettyPrint v0.1.0`
`  [d330b81b] PyPlot v2.8.2`
`  [ce6b1742] RDatasets v0.6.6`
`  [2913bbd2] StatsBase v0.32.1`
`  [fd094767] Suppressor v0.1.1`

`julia> Pkg.build("MLJFlux")`
`  Building Rmath ────→ ~/.julia/packages/Rmath/BoBag/deps/build.log`
`  Building MbedTLS ──→ ~/.julia/packages/MbedTLS/a1JFn/deps/build.log`
`  Building CodecZlib → ~/.julia/packages/CodecZlib/5t9zO/deps/build.log`
`  Building NNlib ────→ ~/.julia/packages/NNlib/3krvM/deps/build.log`
`  Building GR ───────→ ~/.julia/packages/GR/NSt7D/deps/build.log`
`  Building FFMPEG ───→ ~/.julia/packages/FFMPEG/guN1x/deps/build.log`
`  Building Plots ────→ ~/.julia/packages/Plots/12uaJ/deps/build.log`
`  Building Conda ────→ ~/.julia/packages/Conda/3rPhK/deps/build.log`
`  Building PyCall ───→ ~/.julia/packages/PyCall/kAhnQ/deps/build.log`
`false`

In a Jupyter lab:

`using MLJFlux`

`┌ Info: Precompiling MLJFlux [094fc8d1-fd35-5302-93ea-dabda2abf845]`
`└ @ Base loading.jl:1273`
`ERROR: LoadError: UndefVarError: MLJModelInterface not defined`
`Stacktrace:`
` [1] top-level scope at [home]/.julia/packages/MLJModelInterface/BDciB/src/metadata_utils.jl:101`
` [2] eval at ./boot.jl:330 [inlined]`
` [3] eval(::Expr) at [home]/.julia/dev/MLJFlux/src/MLJFlux.jl:1`
` [4] #metadata_model#16(::Type, ::Type, ::Type, ::Bool, ::String, ::String, ::typeof(MLJModelInterface.metadata_model), ::Type) at [home]/.julia/packages/MLJModelInterface/BDciB/src/metadata_utils.jl:110`
` [5] (::MLJModelInterface.var"#kw##metadata_model")(::NamedTuple{(:input, :target, :path, :descr),Tuple{UnionAll,UnionAll,String,String}}, ::typeof(MLJModelInterface.metadata_model), ::Type) at ./none:0`
` [6] top-level scope at [home]/.julia/dev/MLJFlux/src/MLJFlux.jl:306`
` [7] include at ./boot.jl:328 [inlined]`
` [8] include_relative(::Module, ::String) at ./loading.jl:1105`
` [9] include(::Module, ::String) at ./Base.jl:31`
` [10] top-level scope at none:2`
` [11] eval at ./boot.jl:330 [inlined]`
` [12] eval(::Expr) at ./client.jl:425`
` [13] top-level scope at ./none:3`
`in expression starting at [home]/.julia/dev/MLJFlux/src/MLJFlux.jl:306`

`Failed to precompile MLJFlux [094fc8d1-fd35-5302-93ea-dabda2abf845] to [home]/.julia/compiled/v1.3/MLJFlux/fHjkl_0WGeG.ji.`

`Stacktrace:`
` [1] error(::String) at ./error.jl:33`
` [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1283`
` [3] _require(::Base.PkgId) at ./loading.jl:1024`
` [4] require(::Base.PkgId) at ./loading.jl:922`
` [5] require(::Module, ::Symbol) at ./loading.jl:917`
` [6] top-level scope at In[6]:1`

Should I install another package ?

**Comment by ablaom** [comment]
Sorry to hear about your issues. MLJFlux is still very experimental - it does not even have a release yet. It has been in a state of limbo while one of its developers has been busy elsewhere. 

In the meantime, you might try [the dev branch](https://github.com/alan-turing-institute/MLJFlux.jl/pull/6), which is passing travis tests. You can install it from the REPL with `]add MLJFlux#dev`

**Comment by ablaom** [comment]
P.S. Would be good to know if this actually works for you.

**Comment by BenSiv** [comment]
Worked for me. Thanks!
