### ISSUE TITLE
Add coveralls 

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJFlux.jl#9]
I think this would be good to do prior to first release.

**Comment by ayush-1506** [comment]
@ablaom I'm unable to set up codecov since looks like I don't have the required access to install it in this repository from the github marketplace. Maybe you have the permission to do this?

**Comment by ablaom** [comment]
Actually, .travis already generates coverall, and I've added MLJFlux to my coveralls.io repos, which does not seem to require any access I don't have. 

Be great if you can add the readme icon. Here's the template

```
 [![Build Status](https://travis-ci.org/<github username>/<repo name>.svg?branch=master)](https://travis-ci.org/<github username>/<repo name>) [![Coverage Status](https://coveralls.io/repos/github/<github username>/<repo name>/badge.svg?branch=master)](https://coveralls.io/github/<github username>/<repo name>?branch=master)
```
